"""Storage layer - SQLite and ChromaDB."""

# SQLite exports
from .sqlite_db import (
    initialize as initialize_sqlite,
    get_section,
    insert_sections,
    clear_sections,
    clear_usc_title,
    get_usc_sections_for_title,
    delete_usc_sections,
    set_usc_section_hashes,
    count_usc_sections_missing_content_hash,
    search_fulltext,
    get_metadata,
    set_metadata,
    delete_metadata,
    get_usc_title_hashes,
    set_usc_title_hash,
    delete_usc_title_hash,
    clear_usc_title_hashes,
    get_title_toc,
    close as close_sqlite,
)

# ChromaDB exports
from .chroma_client import (
    initialize as initialize_chroma,
    upsert_documents,
    search as search_semantic,
    delete_documents,
    delete_documents_by_source,
    delete_documents_by_source_and_title,
    get_collection_info,
    reset_collection,
    document_exists,
    get_existing_ids,
    truncate_text,
    close as close_chroma,
)

__all__ = [
    # SQLite functions
    "initialize_sqlite",
    "get_section",
    "insert_sections",
    "clear_sections",
    "clear_usc_title",
    "get_usc_sections_for_title",
    "delete_usc_sections",
    "set_usc_section_hashes",
    "count_usc_sections_missing_content_hash",
    "search_fulltext",
    "get_metadata",
    "set_metadata",
    "delete_metadata",
    "get_usc_title_hashes",
    "set_usc_title_hash",
    "delete_usc_title_hash",
    "clear_usc_title_hashes",
    "get_title_toc",
    "close_sqlite",
    # ChromaDB functions
    "initialize_chroma",
    "upsert_documents",
    "search_semantic",
    "delete_documents",
    "delete_documents_by_source",
    "delete_documents_by_source_and_title",
    "get_collection_info",
    "reset_collection",
    "document_exists",
    "get_existing_ids",
    "truncate_text",
    "close_chroma",
]
